[build]
command = "mise install && mise run build -d /tmp/hugo-build-output"
publish = "/tmp/hugo-build-output"

[build.environment]
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"


[context.deploy-preview]
command = "mise install && mise run build --buildFuture -b $DEPLOY_PRIME_URL -d /tmp/hugo-build-output"
publish = "/tmp/hugo-build-output"

[context.branch-deploy]
command = "mise install && mise run build -b $DEPLOY_PRIME_URL -d /tmp/hugo-build-output"
publish = "/tmp/hugo-build-output"
